In [1]:
import pandas as pd

df = pd.read_csv("dataset/synthetic_logs.csv")
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

System from which logs are coming

In [2]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [3]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [4]:
df[df.target_label=='System Notification'].sample(10)

,timestamp,source,log_message,target_label,complexity
1187,7/3/2025 3:50,ModernHR,System updated to version 3.3.6.,System Notification,regex
1148,8/13/2025 10:57,ThirdPartyAPI,Backup ended at 2025-08-22 12:30:23.,System Notification,regex
1463,7/29/2025 16:20,ThirdPartyAPI,File data_2288.csv uploaded successfully by us...,System Notification,regex
1406,5/20/2025 11:05,ThirdPartyAPI,Backup started at 2025-09-05 04:17:13.,System Notification,regex
1910,6/8/2025 13:52,ThirdPartyAPI,File data_6245.csv uploaded successfully by us...,System Notification,regex
1902,4/21/2025 17:32,AnalyticsEngine,Backup completed successfully.,System Notification,regex
325,6/2/2025 12:18,ThirdPartyAPI,Backup ended at 2025-07-18 17:06:54.,System Notification,regex
2192,12/28/2025 19:20,ModernCRM,Disk cleanup completed successfully.,System Notification,regex
1542,11/8/2025 20:19,BillingSystem,Disk cleanup completed successfully.,System Notification,regex
1921,11/21/2025 4:16,AnalyticsEngine,System updated to version 1.5.7.,System Notification,regex